const {chromium}=require(process.env.PLAYWRIGHT_MODULE || '/Users/puskar/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"});
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto((process.env.ASFAR_TEST_URL || 'http://127.0.0.1:8877/'),{waitUntil:'networkidle'});
 assert.equal(await page.locator(".mt-hero__slide").count(),3);
 await page.locator(".mt-hero__dot").nth(1).click();
 await page.waitForTimeout(650);
 assert.equal(await page.locator(".mt-hero__dot.mt-is-active").getAttribute('data-i'),'1');
 assert.equal(await page.locator(".mt-hero__dot").nth(1).getAttribute('aria-pressed'),'true');
 await page.locator(".mt-hero__dot").first().click();
 console.log('PASS: Banner dots select the matching slide and remain selected');
 await page.locator("#burger").click();
 assert.equal(await page.locator("#burger").getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator("#menu .mt-menu__links a").count(),8);
 await page.keyboard.press('Escape');
 console.log('PASS: Native WordPress drawer menu opens and closes');
 console.log('EN title',await page.title());
 console.log('Visible headline',await page.locator('h1').first().textContent());
 console.log('News cards',await page.locator(".mt-dk-newscard").count(),'Team',await page.locator(".mt-member--opens").count());
 await page.locator('img').evaluateAll(es=>es.forEach(e=>e.loading='eager')); await page.waitForTimeout(1200); console.log('Broken loaded images',await page.locator('img').evaluateAll(es=>es.filter(e=>e.getAttribute('src')&&e.complete&&!e.naturalWidth).map(e=>e.src))); console.log('App loaded',await page.evaluate(()=>typeof window.__dk));
 await page.screenshot({path:'/private/tmp/asfar-en.png',fullPage:true}); await page.screenshot({path:'/private/tmp/asfar-en-hero.png'});
 await page.locator("#dkSectors").screenshot({path:'/private/tmp/asfar-sectors.png'});
 await page.locator("#dkFaq .mt-dk-faq__btn").first().click();
 assert.equal(await page.locator("#dkFaq .mt-dk-faq__btn").first().getAttribute('aria-expanded'),'true');
 await page.locator("#enquireBtn").click();
 assert.equal(await page.locator("#enquireBtn").getAttribute('aria-expanded'),'true');
 assert.equal(await page.locator('footer').count(),1);
 console.log('PASS: FAQ and shared footer contact form open');
 await page.locator("#contactForm [name=name]").fill('Local theme verification');
 await page.locator("#contactForm [name=email]").fill('local-test@example.invalid');
 await page.locator("#contactForm [name=message]").fill('Local fixture submission; mail is disabled.');
 const submission=page.waitForResponse(r=>r.url().includes('admin-ajax.php') && r.request().method()==='POST');
 await page.locator("#contactForm [type=submit]").click();
 const saved=await (await submission).json();
 assert.equal(saved.success,true);
 console.log('PASS: Contact form saves through the WordPress endpoint');
 const ar=await page.locator(".mt-nav__lang a").getAttribute('href');
 await page.goto(ar,{waitUntil:'networkidle'});
 assert.equal(await page.locator("#enquireBtn").innerText(),'تواصل معنا');
 assert.equal(await page.locator('footer').count(),1);
 assert.equal(await page.locator("#dkTeam .mt-member--opens").count(),19);
 console.log('AR direction',await page.locator('html').getAttribute('dir'));
 console.log('AR headline',await page.locator('h1').first().textContent());
 await page.setViewportSize({width:390,height:844});
 await page.locator('img').evaluateAll(es=>es.forEach(e=>e.loading='eager')); await page.waitForTimeout(1000); await page.screenshot({path:'/private/tmp/asfar-ar-mobile.png',fullPage:true}); await page.screenshot({path:'/private/tmp/asfar-ar-hero.png'});
 await page.locator("#dkSectors").screenshot({path:'/private/tmp/asfar-sectors-mobile.png'});
 console.log('Mobile widths',await page.evaluate(()=>[innerWidth,document.documentElement.scrollWidth]));

 const urls=JSON.parse(fs.readFileSync('/private/tmp/asfar-urls.json','utf8'));
 const failures=[];
 for(const [slug,url] of Object.entries(urls)){const r=await page.request.get(url);const html=await r.text();if(r.status()!==200||!html.includes('</html>')||html.includes('There has been a critical error'))failures.push([slug,r.status()]);}
 assert.deepEqual(failures,[]);
 console.log('All existing page smoke failures',failures);
 const newUrls=JSON.parse(fs.readFileSync('/private/tmp/asfar-new-urls.json','utf8'));
 for(const url of Object.values(newUrls)){const r=await page.request.get(url);assert.equal(r.status(),200);assert.ok((await r.text()).includes('</html>'));}
 await page.goto(newUrls.faq_en,{waitUntil:'networkidle'});
 await page.locator("#dkFaq .mt-dk-faq__btn").first().click();
 assert.equal(await page.locator("#dkFaq .mt-dk-faq__btn").first().getAttribute('aria-expanded'),'true');
 console.log('PASS: New project, member and FAQ pages render; standalone FAQ expands');
 await page.goto(urls.team,{waitUntil:'networkidle'});
 await page.locator(".mt-member__name").first().click();
 console.log('Team biography opens',await page.locator(".mt-mexp").evaluate(e=>e.classList.contains("mt-is-open")));
 await page.keyboard.press('Escape');
 console.log('Team biography closes',await page.locator(".mt-mexp").evaluate(e=>!e.classList.contains("mt-is-open")));
 await page.goto('http://127.0.0.1:8877/?p=999999');
 console.log('404 template',await page.locator('h1').textContent());
 assert.deepEqual(errors,[]);
 console.log('JS errors',errors);
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
